apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-gpu
  namespace: scott
  labels:
    app: jupyter-gpu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter-gpu
  template:
    metadata:
      labels:
        app: jupyter-gpu
    spec:
      containers:
      - name: ctnr-kml-gpu-jupyter-lab
        image: scottmlittle/ctnr-kml-gpu-jupyter-lab:r7.0.18
        ports:
        - containerPort: 8888
---
kind: Service
apiVersion: v1
metadata:
  name: jupyter-gpu
  namespace: scott
spec:
  type: NodePort
  selector:
    app: jupyter-gpu
  ports:
  - protocol: TCP
    nodePort: 30040
    port: 8888
    targetPort: 8888